### PR TITLE
Fixes/156 166

### LINKED ISSUE #156: small tweak for plugins shown in webview
Instead of sliding the webview from the right, make it slide from the bottom, it takes more time but that's good because it takes time to load the plugin.

Also, instead of the left arrow top left to close (which is very annoying as it forces the plugin to add a lot of top padding), replace that with a cross top right. Easier to keep that space empty.

https://github.com/user-attachments/assets/319e8e4b-ded6-4f63-a5ec-112ba7b8a27a

### LINKED ISSUE #166: Implement new More actions button UX. This is where the plugins live
https://www.notion.so/citizenwallet/Implement-new-More-actions-button-UX-This-is-where-the-plugins-live-e73e417a66a3495fbf1bc97533869321?pvs=4

Screenshot 2024-09-27 at 10 15 16

### LINKED ISSUE #170: More button
It's not a primary action, so it shouldn't be in plein blue like the Send and Receive buttons.

See figma:
Home Screen - _More_ Open

Also, there shouldn't be any animation when loading. Just show the button directly like the other buttons.

https://github.com/user-attachments/assets/c83e02a5-94a2-4df1-87b5-907df93b4a6b

### PR DESCRIPTION
**Pull request by SajeeTechi**
closes #156 
closes #166 
closes #170

### CODE REVIEW

File: lib/router/router.dart [hunk 1]
```diff
@@ -316,19 +316,36 @@ GoRouter createRouter(
...
-                }
+              pageBuilder: (context, state) {
 
                 final extra = state.extra as Map<String, dynamic>;
 
-                return WebViewScreen(
-                  url: extra['url'],
-                  redirectUrl: extra['redirectUrl'],
-                  customScheme: extra['customScheme'],
+                return CustomTransitionPage(
```
Comment (kevtechi) [inline lib/router/router.dart:323]: Since we switched to using a modal, we don't need this route anymore, do we?

File: lib/state/wallet/logic.dart [hunk 2]
```diff
@@ -1793,4 +1794,54 @@ class WalletLogic extends WidgetsBindingObserver {
...
+  }
+
+  Future<void> evaluateWalletActions() async {
+    _state.setWalletActionsLoading(true);
+
+    _state.walletActions = [];
+
+    List<ActionButton> actionsToAdd = [];
+
+    final showVouchers = selectShowVouchers(_state);
```
Comment (kevtechi) [inline lib/state/wallet/logic.dart:1809]: vouchers can always be shown. The underlying conditions that are being checked are not really important.

File: lib/state/wallet/logic.dart [hunk 3]
```diff
@@ -1793,4 +1794,54 @@ class WalletLogic extends WidgetsBindingObserver {
...
+    final showMinter = selectShowMinter(_state);
```
Comment (kevtechi) [inline lib/state/wallet/logic.dart:1810]: I would just make the network request to check if the user has the minter role here and based on the response, add the button.

Remove the network call from the other place it is being done.

File: lib/state/wallet/logic.dart [hunk 4]
```diff
@@ -1793,4 +1794,54 @@ class WalletLogic extends WidgetsBindingObserver {
...
+    final showPlugins = selectShowPlugins(_state);
```
Comment (kevtechi) [inline lib/state/wallet/logic.dart:1811]: Just fetch the plugins from the config here and evaluate.

File: lib/state/wallet/logic.dart [hunk 5]
```diff
@@ -1793,4 +1794,54 @@ class WalletLogic extends WidgetsBindingObserver {
...
+    _state.setWalletActionsLoading(loading);
+  }
+
+  Future<void> evaluateWalletActions() async {
+    _state.setWalletActionsLoading(true);
+
+    _state.walletActions = [];
+
+    List<ActionButton> actionsToAdd = [];
+
```
Comment (kevtechi) [inline lib/state/wallet/logic.dart:1808]: Just a general comment here, selectors are meant to be a result of state. State is something that tells the UI what to render.

So, I wouldn't rely on checking those properties here. Rather pass them in from the UI if needed. 

But in the 3 cases below, there's a solution for all of them.

File: lib/state/wallet/logic.dart [hunk 6]
```diff
@@ -1793,4 +1794,54 @@ class WalletLogic extends WidgetsBindingObserver {
...
+    if (actionsToAdd.length > 1) {
+      actionsToAdd.add(ActionButton(
+        label: 'More',
+        buttonType: ActionButtonType.more,
+      ));
+    }
+
+    _state.walletActions = actionsToAdd;
+
+    await delay(const Duration(milliseconds: 500));
```
Comment (kevtechi) [inline lib/state/wallet/logic.dart:1843]: I'm guessing that this had something to do with the animation or the fact that the values hadn't updated yet. 

If you make the changes above, you shouldn't need this.

File: lib/state/wallet/selectors.dart [hunk 7]
```diff
@@ -71,3 +72,71 @@ Map<String, List<CWWallet>> selectSortedGroupedWalletsByAlias(
...
+  }
+
+  if (state.wallet!.plugins.isEmpty) {
+    return false;
+  }
+
+  return true;
+}
+
+ActionButton? selectActionButtonToShow(WalletState state) {
```
Comment (kevtechi) [inline lib/state/wallet/selectors.dart:128]: This is probably the only selector you need to keep.

File: lib/state/wallet/logic.dart [hunk 8]
```diff
@@ -1793,4 +1794,54 @@ class WalletLogic extends WidgetsBindingObserver {
...
+    }
+
+    if (actionsToAdd.length > 1) {
+      actionsToAdd.add(ActionButton(
+        label: 'More',
+        buttonType: ActionButtonType.more,
+      ));
+    }
+
+    _state.walletActions = actionsToAdd;
```
Comment (kevtechi) [inline lib/state/wallet/logic.dart:1841]: Never assigned directly. Do it through a function in `state`. 

For ex, you could have `_state.walletActionsLoadingSuccess(actionsToAdd);` which both sets loading to false and assigns the actions to the property.

File: lib/state/wallet/state.dart [hunk 9]
```diff
@@ -620,4 +640,10 @@ class WalletState with ChangeNotifier {
 
     notifyListeners();
   }
+
+  void setWalletActionsLoading(bool loading) {
```
Comment (kevtechi) [inline lib/state/wallet/state.dart:644]: As mentioned above, you can probably modify this. 

The pattern for loading stuff is usually:
- `walletActionsRequest();` >> set loading = true
- `walletActionsSuccess(List<ActionButton>);` >> set loading = false, walletActions = ...
- `walletActionsFail()` >> set loading = false

Since you are making a network request to check the minter role, you might need a try/catch

**Review by kevtechi — CHANGES_REQUESTED** [review]

File: lib/router/router.dart (hunk 1 above)
Comment (SajeeTechi) [reply lib/router/router.dart:323]: in the send_details screen I now changed it to use the webview modal to show community topup screen

File: lib/state/wallet/selectors.dart [hunk 10]
```diff
@@ -71,3 +72,71 @@ Map<String, List<CWWallet>> selectSortedGroupedWalletsByAlias(
         })
         .sortedBy((w) => w.alias.toLowerCase())
         .groupListsBy((w) => w.alias.toLowerCase());
+
+bool selectShowVouchers(WalletState state) {
```
Comment (kevtechi) [inline lib/state/wallet/selectors.dart:76]: do we need these selectors anymore

File: lib/state/wallet/logic.dart [hunk 11]
```diff
@@ -1793,4 +1792,50 @@ class WalletLogic extends WidgetsBindingObserver {
...
+
+      if (isMinter) {
+        actionsToAdd.add(ActionButton(
+          label: 'Minter',
+          buttonType: ActionButtonType.minter,
+        ));
+      }
+    } catch (_) {}
+
+    List<PluginConfig> plugins = _state.config!.plugins;
```
Comment (kevtechi) [inline lib/state/wallet/logic.dart:1824]: Again, don't read from state. Actually read the config. You can get it from the db, since you have a table for it.

**Review by kevtechi — CHANGES_REQUESTED** [review]

File: lib/state/wallet/logic.dart [hunk 12]
```diff
@@ -1793,4 +1792,59 @@ class WalletLogic extends WidgetsBindingObserver {
...
+      if (isMinter) {
+        actionsToAdd.add(ActionButton(
+          label: 'Minter',
+          buttonType: ActionButtonType.minter,
+        ));
+      }
+    } catch (_) {}
+
+    try {
+      final alias = _state.config?.community.alias ?? '';
```
Comment (kevtechi) [inline lib/state/wallet/logic.dart:1825]: final alias = _wallet.alias;

**Review by kevtechi — CHANGES_REQUESTED** [review]

**Review by kevtechi — APPROVED** [review]
